modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="skyblock_resources"
version="1.1.1"
displayName="Skyblock Resources"
displayURL="https://drakma.tv"
credits="Drakma"
authors="Drakma"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.skyblock_resources]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.skyblock_resources]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.skyblock_resources]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration