package net.drakma.skyblockresources.block.listener;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.drakma.skyblockresources.init.SkyblockResourcesModBlockEntities;
import net.drakma.skyblockresources.block.renderer.WoodenTuffGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenSoulsandGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenSlimeGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenSandGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenNetherrackGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenGravelGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenGraniteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenEndStoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenEmptyGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenDripstoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenDirtGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenDioriteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenDeepslateGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenCobblestoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenClayGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenCalciteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenBlackstoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenBasaltGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.WoodenAndesiteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneTuffGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneSoulsandGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneSlimeGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneSandGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneNetherrackGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneGravelGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneGraniteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneEndStoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneEmptyGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneDripstoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneDirtGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneDioriteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneDeepslateGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneCobblestoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneClayGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneCalciteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneBlackstoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneBasaltGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.StoneAndesiteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteTuffGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteSoulsandGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteSlimeGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteSandGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteNetherrackGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteGravelGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteGraniteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteEndStoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteEmptyGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteDripstoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteDirtGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteDioriteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteDeepslateGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteCobblestoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteClayGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteCalciteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteBlackstoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteBasaltGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.NetheriteAndesiteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronTuffGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronSoulsandGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronSlimeGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronSandGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronNetherrackGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronGravelGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronGraniteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronEndStoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronEmptyGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronDripstoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronDirtGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronDioriteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronDeepslateGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronCobblestoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronClayGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronCalciteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronBlackstoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronBasaltGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.IronAndesiteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldTuffGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldSoulsandGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldSlimeGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldSandGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldNetherrackGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldGravelGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldGraniteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldEndStoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldEmptyGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldDripstoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldDirtGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldDioriteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldDeepslateGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldCobblestoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldClayGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldCalciteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldBlackstoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldBasaltGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.GoldAndesiteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondTuffGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondSoulsandGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondSlimeGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondSandGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondNetherrackGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondGravelGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondGraniteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondEndStoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondEmptyGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondDripstoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondDirtGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondDioriteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondDeepslateGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondCobblestoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondClayGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondCalciteGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondBlackstoneGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondBasaltGeneratorTileRenderer;
import net.drakma.skyblockresources.block.renderer.DiamondAndesiteGeneratorTileRenderer;
import net.drakma.skyblockresources.SkyblockResourcesMod;

@Mod.EventBusSubscriber(modid = SkyblockResourcesMod.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ClientListener {
	@OnlyIn(Dist.CLIENT)
	@SubscribeEvent
	public static void registerRenderers(EntityRenderersEvent.RegisterRenderers event) {
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_BASALT_GENERATOR.get(), context -> new WoodenBasaltGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_BLACKSTONE_GENERATOR.get(), context -> new WoodenBlackstoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_COBBLESTONE_GENERATOR.get(), context -> new WoodenCobblestoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_DEEPSLATE_GENERATOR.get(), context -> new WoodenDeepslateGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_DIORITE_GENERATOR.get(), context -> new WoodenDioriteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_DIRT_GENERATOR.get(), context -> new WoodenDirtGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_GRANITE_GENERATOR.get(), context -> new WoodenGraniteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_GRAVEL_GENERATOR.get(), context -> new WoodenGravelGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_NETHERRACK_GENERATOR.get(), context -> new WoodenNetherrackGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_SAND_GENERATOR.get(), context -> new WoodenSandGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_SOULSAND_GENERATOR.get(), context -> new WoodenSoulsandGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_TUFF_GENERATOR.get(), context -> new WoodenTuffGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_ANDESITE_GENERATOR.get(), context -> new WoodenAndesiteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_ANDESITE_GENERATOR.get(), context -> new StoneAndesiteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_BASALT_GENERATOR.get(), context -> new StoneBasaltGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_BLACKSTONE_GENERATOR.get(), context -> new StoneBlackstoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_COBBLESTONE_GENERATOR.get(), context -> new StoneCobblestoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_DEEPSLATE_GENERATOR.get(), context -> new StoneDeepslateGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_DIORITE_GENERATOR.get(), context -> new StoneDioriteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_DIRT_GENERATOR.get(), context -> new StoneDirtGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_GRANITE_GENERATOR.get(), context -> new StoneGraniteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_GRAVEL_GENERATOR.get(), context -> new StoneGravelGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_NETHERRACK_GENERATOR.get(), context -> new StoneNetherrackGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_SAND_GENERATOR.get(), context -> new StoneSandGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_SOULSAND_GENERATOR.get(), context -> new StoneSoulsandGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_TUFF_GENERATOR.get(), context -> new StoneTuffGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_ANDESITE_GENERATOR.get(), context -> new IronAndesiteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_BASALT_GENERATOR.get(), context -> new IronBasaltGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_BLACKSTONE_GENERATOR.get(), context -> new IronBlackstoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_COBBLESTONE_GENERATOR.get(), context -> new IronCobblestoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_DEEPSLATE_GENERATOR.get(), context -> new IronDeepslateGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_DIORITE_GENERATOR.get(), context -> new IronDioriteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_DIRT_GENERATOR.get(), context -> new IronDirtGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_GRANITE_GENERATOR.get(), context -> new IronGraniteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_GRAVEL_GENERATOR.get(), context -> new IronGravelGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_NETHERRACK_GENERATOR.get(), context -> new IronNetherrackGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_SAND_GENERATOR.get(), context -> new IronSandGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_SOULSAND_GENERATOR.get(), context -> new IronSoulsandGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_TUFF_GENERATOR.get(), context -> new IronTuffGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_ANDESITE_GENERATOR.get(), context -> new GoldAndesiteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_BASALT_GENERATOR.get(), context -> new GoldBasaltGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_BLACKSTONE_GENERATOR.get(), context -> new GoldBlackstoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_COBBLESTONE_GENERATOR.get(), context -> new GoldCobblestoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_DEEPSLATE_GENERATOR.get(), context -> new GoldDeepslateGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_DIORITE_GENERATOR.get(), context -> new GoldDioriteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_DIRT_GENERATOR.get(), context -> new GoldDirtGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_GRANITE_GENERATOR.get(), context -> new GoldGraniteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_GRAVEL_GENERATOR.get(), context -> new GoldGravelGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_NETHERRACK_GENERATOR.get(), context -> new GoldNetherrackGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_SAND_GENERATOR.get(), context -> new GoldSandGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_SOULSAND_GENERATOR.get(), context -> new GoldSoulsandGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_TUFF_GENERATOR.get(), context -> new GoldTuffGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_ANDESITE_GENERATOR.get(), context -> new DiamondAndesiteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_BASALT_GENERATOR.get(), context -> new DiamondBasaltGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_BLACKSTONE_GENERATOR.get(), context -> new DiamondBlackstoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_COBBLESTONE_GENERATOR.get(), context -> new DiamondCobblestoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_DEEPSLATE_GENERATOR.get(), context -> new DiamondDeepslateGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_DIORITE_GENERATOR.get(), context -> new DiamondDioriteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_DIRT_GENERATOR.get(), context -> new DiamondDirtGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_GRANITE_GENERATOR.get(), context -> new DiamondGraniteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_GRAVEL_GENERATOR.get(), context -> new DiamondGravelGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_NETHERRACK_GENERATOR.get(), context -> new DiamondNetherrackGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_SAND_GENERATOR.get(), context -> new DiamondSandGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_SOULSAND_GENERATOR.get(), context -> new DiamondSoulsandGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_TUFF_GENERATOR.get(), context -> new DiamondTuffGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_ANDESITE_GENERATOR.get(), context -> new NetheriteAndesiteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_BASALT_GENERATOR.get(), context -> new NetheriteBasaltGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_BLACKSTONE_GENERATOR.get(), context -> new NetheriteBlackstoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_COBBLESTONE_GENERATOR.get(), context -> new NetheriteCobblestoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_DEEPSLATE_GENERATOR.get(), context -> new NetheriteDeepslateGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_DIORITE_GENERATOR.get(), context -> new NetheriteDioriteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_GRAVEL_GENERATOR.get(), context -> new NetheriteGravelGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_DIRT_GENERATOR.get(), context -> new NetheriteDirtGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_GRANITE_GENERATOR.get(), context -> new NetheriteGraniteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_NETHERRACK_GENERATOR.get(), context -> new NetheriteNetherrackGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_SAND_GENERATOR.get(), context -> new NetheriteSandGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_SOULSAND_GENERATOR.get(), context -> new NetheriteSoulsandGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_TUFF_GENERATOR.get(), context -> new NetheriteTuffGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_EMPTY_GENERATOR.get(), context -> new WoodenEmptyGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_CALCITE_GENERATOR.get(), context -> new WoodenCalciteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_DRIPSTONE_GENERATOR.get(), context -> new WoodenDripstoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_END_STONE_GENERATOR.get(), context -> new WoodenEndStoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_SLIME_GENERATOR.get(), context -> new WoodenSlimeGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.WOODEN_CLAY_GENERATOR.get(), context -> new WoodenClayGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_CALCITE_GENERATOR.get(), context -> new StoneCalciteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_CLAY_GENERATOR.get(), context -> new StoneClayGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_END_STONE_GENERATOR.get(), context -> new StoneEndStoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_DRIPSTONE_GENERATOR.get(), context -> new StoneDripstoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_SLIME_GENERATOR.get(), context -> new StoneSlimeGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.STONE_EMPTY_GENERATOR.get(), context -> new StoneEmptyGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_CALCITE_GENERATOR.get(), context -> new IronCalciteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_CLAY_GENERATOR.get(), context -> new IronClayGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_DRIPSTONE_GENERATOR.get(), context -> new IronDripstoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_END_STONE_GENERATOR.get(), context -> new IronEndStoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_SLIME_GENERATOR.get(), context -> new IronSlimeGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.IRON_EMPTY_GENERATOR.get(), context -> new IronEmptyGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_EMPTY_GENERATOR.get(), context -> new GoldEmptyGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_EMPTY_GENERATOR.get(), context -> new DiamondEmptyGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_CALCITE_GENERATOR.get(), context -> new GoldCalciteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_CLAY_GENERATOR.get(), context -> new GoldClayGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_DRIPSTONE_GENERATOR.get(), context -> new GoldDripstoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_END_STONE_GENERATOR.get(), context -> new GoldEndStoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.GOLD_SLIME_GENERATOR.get(), context -> new GoldSlimeGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_EMPTY_GENERATOR.get(), context -> new NetheriteEmptyGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_CALCITE_GENERATOR.get(), context -> new DiamondCalciteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_CLAY_GENERATOR.get(), context -> new DiamondClayGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_DRIPSTONE_GENERATOR.get(), context -> new DiamondDripstoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_END_STONE_GENERATOR.get(), context -> new DiamondEndStoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.DIAMOND_SLIME_GENERATOR.get(), context -> new DiamondSlimeGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_CALCITE_GENERATOR.get(), context -> new NetheriteCalciteGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_CLAY_GENERATOR.get(), context -> new NetheriteClayGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_DRIPSTONE_GENERATOR.get(), context -> new NetheriteDripstoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_END_STONE_GENERATOR.get(), context -> new NetheriteEndStoneGeneratorTileRenderer());
		event.registerBlockEntityRenderer(SkyblockResourcesModBlockEntities.NETHERITE_SLIME_GENERATOR.get(), context -> new NetheriteSlimeGeneratorTileRenderer());
	}
}
