
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.drakma.skyblockresources.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.drakma.skyblockresources.SkyblockResourcesMod;

public class SkyblockResourcesModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, SkyblockResourcesMod.MODID);
	public static final RegistryObject<CreativeModeTab> SKYBLOCK_RESOURCES = REGISTRY.register("skyblock_resources",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.skyblock_resources.skyblock_resources")).icon(() -> new ItemStack(Blocks.ROOTED_DIRT)).displayItems((parameters, tabData) -> {
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_EMPTY_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_EMPTY_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_EMPTY_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_EMPTY_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_EMPTY_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_EMPTY_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModItems.STONE_UPGRADE_CARD.get());
				tabData.accept(SkyblockResourcesModItems.IRON_UPGRADE_CARD.get());
				tabData.accept(SkyblockResourcesModItems.GOLD_UPGRADE_CARD.get());
				tabData.accept(SkyblockResourcesModItems.DIAMOND_UPGRADE_CARD.get());
				tabData.accept(SkyblockResourcesModItems.NETHERITE_UPGRADE_CARD.get());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_ANDESITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_ANDESITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_ANDESITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_ANDESITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_ANDESITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_ANDESITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_BASALT_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_BASALT_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_BASALT_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_BASALT_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_BASALT_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_BASALT_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_BLACKSTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_BLACKSTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_BLACKSTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_BLACKSTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_BLACKSTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_BLACKSTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_CALCITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_CALCITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_CALCITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_CALCITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_CALCITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_CALCITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_CLAY_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_CLAY_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_CLAY_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_CLAY_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_CLAY_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_CLAY_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_COBBLESTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_COBBLESTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_COBBLESTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_COBBLESTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_COBBLESTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_COBBLESTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_DEEPSLATE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_DEEPSLATE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_DEEPSLATE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_DEEPSLATE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_DEEPSLATE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_DEEPSLATE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_DIORITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_DIORITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_DIORITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_DIORITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_DIORITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_DIORITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_DIRT_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_DIRT_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_DIRT_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_DIRT_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_DIRT_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_DIRT_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_DRIPSTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_DRIPSTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_DRIPSTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_DRIPSTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_DRIPSTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_DRIPSTONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_END_STONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_END_STONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_END_STONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_END_STONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_END_STONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_END_STONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_GRANITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_GRANITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_GRANITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_GRANITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_GRANITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_GRANITE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_GRAVEL_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_GRAVEL_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_GRAVEL_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_GRAVEL_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_GRAVEL_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_GRAVEL_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_NETHERRACK_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_NETHERRACK_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_NETHERRACK_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_NETHERRACK_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_NETHERRACK_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_NETHERRACK_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_SAND_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_SAND_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_SAND_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_SAND_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_SAND_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_SAND_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_SLIME_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_SLIME_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_SLIME_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_SLIME_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_SLIME_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_SLIME_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_SOULSAND_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_SOULSAND_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_SOULSAND_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_SOULSAND_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_SOULSAND_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_SOULSAND_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_TUFF_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_TUFF_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_TUFF_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_TUFF_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_TUFF_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_TUFF_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_SKY_STONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_SKY_STONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_SKY_STONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_SKY_STONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_SKY_STONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_SKY_STONE_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.WOODEN_DUST_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.STONE_DUST_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.IRON_DUST_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.GOLD_DUST_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.DIAMOND_DUST_GENERATOR.get().asItem());
				tabData.accept(SkyblockResourcesModBlocks.NETHERITE_DUST_GENERATOR.get().asItem());
			}).withSearchBar().build());
}
